#!/usr/bin/env php
<?php

require_once __DIR__ . '/../../autoload.php';

use w3lifer\yii2\DocBookmarks;

$docBookmarks = new DocBookmarks();

file_put_contents(
    __DIR__ . '/../../../yii2-doc-bookmarks-as-array.php',
    '<?php' . "\n\n" .
        var_export($docBookmarks->getAsArray(), true) . ';'
);

file_put_contents(
    __DIR__ . '/../../../yii2-doc-bookmarks-as-netscape-bookmarks.html',
    $docBookmarks->getAsNetscapeBookmarks()
);

echo 'Done!' . "\n";
